server:
  port: ${PORT:8081}
  servlet:
    context-path:
spring:
  liquibase:
    enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:0}

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false

  jackson:
    serialization:
      indent_output: true

jwt:
  header: Authorization
  secret: proselyte
  expiration: 604800
