server:
  port: 8080
  servlet:
    context-path:
spring:

#  thymeleaf:
#    encoding: UTF-8
#    prefix: file:ui-service/src/main/resources/templates/
#    cache: false
#  resources:
#    static-locations: file:ui-service/src/main/resources/static/

  jackson:
    serialization:
      indent_output: true
