server:
  port: 8080
  servlet:
    context-path:


  #  thymeleaf:
#    encoding: UTF-8
#    prefix: file:ui-service/src/main/resources/templates/
#    cache: false
#  resources:
#    static-locations: file:ui-service/src/main/resources/static/



jwt:
  header: Authorization
  secret: proselyte
  expiration: 604800
